version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/apps
hooks:
  AfterInstall:
   - location: scripts/copy_dist
     timeout: 3000
     runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  